### ISSUE TITLE
Учет соседних дней. 

### ISSUE THREAD

**Issue by Sergio-tekilla** [walpurgicC/testTaskQt#1]
Добрый день! 

Спасибо за оперативное решение задачи.  Появился следующий вопрос: 
если файл лога будет содержать более одного дня, а автомобиль находился в движении около полуночи, то как будет учитываться время стоянки/движения? 
Нужно ли вносить изменения в программу для учета данного поведения?

С уважением, Сергей Котляр
Команда Старлайн Мастер

**Comment by walpurgicC** [comment]
Здравствуйте. Если автомобиль будет находится в движении более одного дня, то изменения в коде будут минимальны, а конкретно, в QMap потребуется хранить не QTime, а QDateTime в качестве ключа, а в файле csvParser потребуется изменить строку "QTime     time   { QDateTime::fromString(parsed[0], "\"yyyy-MM-dd HH:mm:ss\"").time() };" на что-то вроде "QDateTime     dateTime   { QDateTime::fromString(parsed[0], "\"yyyy-MM-dd HH:mm:ss\"") };".
Но, таким образом, потребуется немного исправить обработчик времени простоя, так как оно сейчас не считается отдельно, а считается из расчета 23:59:59 - время в пути. Возможным вариантом решения может быть либо добавление расчета простоя исходя из скорости и времени разрыва логов, аналогично подсчету времени в пути, либо же, например, подсчет количества суток, которые логировались для автомобиля, и соответственно, 23:59:59 * кол-во суток - время в пути. 
Немного не понял вопроса по поводу "находился в движении около полуночи", уточните, пожалуйста.

**Comment by walpurgicC** [comment]
Если я правильно понял вопрос, то никаких изменений по поводу учета времени движения от, например, 23.59 предыдущего дня до 00.01 не потребуется, так как QDateTime так же поддерживает QDateTime::secsTo(), который используется в алгоритме.

**Comment by Sergio-tekilla** [comment]
Да, вопрос был именно про интервал 23:59 - 00.01 следующего дня. 

И он касался именно этой части кода : 
~~~
QTime     time   { QDateTime::fromString(parsed[0], "\"yyyy-MM-dd HH:mm:ss\"").time() };
~~~

**Comment by Sergio-tekilla** [comment]
Спасибо, у меня больше нет вопросов.
